title: Welcome to the Lumini's blog
theme: minima
author: Lumini Nanayakkara
email: lumininanayakkaraln@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Lumini Nanayakkara. I am studying Software Engineering at SLIIT. I like to be a good Software Engineer. I like to work with new technologies. 

# social links
linkedIn_username: Lumini Nanayakkara
github_username:  LuminiNanayakkara

show_excerpts: true # set to false to remove excerpts on the homepage
